
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import APpProvider from "@/redux/features/provider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: ` Webmaxi | Home`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`className.Inter`}>
        <APpProvider>

        {children}
        </APpProvider>
        </body>
    </html>
  );
}
